<script type='text/javascript' src="{{ asset('/fullcalendar4.1/rrule/rrule.js') }}"></script>
<script type='text/javascript' src="{{ asset('/fullcalendar4.1/core/main.js') }}"></script>
<script type='text/javascript' src="{{ asset('/fullcalendar4.1/daygrid/main.js') }}"></script>
<script type='text/javascript' src="{{ asset('/fullcalendar4.1/rrule/main.js') }}"></script>
<script type='text/javascript' src="{{ asset('/fullcalendar4.1/interaction/main.js') }}"></script>
<script type='text/javascript' src="{{ asset('/fullcalendar4.1/list/main.js') }}"></script>
<script type='text/javascript' src="{{ asset('/fullcalendar4.1/timegrid/main.js') }}"></script>
<script type='text/javascript' src="{{ asset('/js/moment.js') }}"></script>
<script type='text/javascript' src="{{ asset('/fullcalendar4.1/moment/main.min.js') }}"></script>
<script type='text/javascript' src="{{ asset('/fullcalendar4.1/moment-timezone/main.min.js') }}"></script>
<script type='text/javascript' src="{{ asset('/js/launchpad/appointments.js') }}"></script>